<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rm9C_0ZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Rm9C.0Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rm9C.0Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'catRepo' => ['privates', 'App\\Repository\\CategorieArticleRepository', 'getCategorieArticleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'imageRepo' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
        ], [
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'catRepo' => 'App\\Repository\\CategorieArticleRepository',
            'em' => '?',
            'imageRepo' => 'App\\Repository\\ImageRepository',
        ]);
    }
}
