<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VOA1iBtService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.VOA1iBt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VOA1iBt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'evRipo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'userRipo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'evRipo' => 'App\\Repository\\EvenementRepository',
            'userRipo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
