<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D1ryQXTService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.d1ryQXT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d1ryQXT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoP' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'repoP' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
