<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MXGvpR2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.mXGvpR2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mXGvpR2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commRepo' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'payement' => ['privates', '.errored.Rbt0ZAO', NULL, 'Cannot determine controller argument for "App\\Controller\\CommandeController::addCommande()": the $payement argument is type-hinted with the non-existent class or interface: "App\\Service\\PayTech\\Payement".'],
            'prodRepo' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'commRepo' => 'App\\Repository\\CommandeRepository',
            'em' => '?',
            'payement' => '?',
            'prodRepo' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
