<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Ak1DXLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.0Ak1DXL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Ak1DXL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comRepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'sujetRepo' => ['privates', 'App\\Repository\\SujetRepository', 'getSujetRepositoryService', true],
        ], [
            'comRepo' => 'App\\Repository\\CommentaireRepository',
            'em' => '?',
            'sujetRepo' => 'App\\Repository\\SujetRepository',
        ]);
    }
}
