<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X8iayQService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.x_8iayQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x_8iayQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comRepo' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'comRepo' => 'App\\Repository\\CommandeRepository',
            'paginator' => '?',
        ]);
    }
}
