<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_93Njn1OService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.93Njn1O' shared service.
     *
     * @return \App\Service\PayTech\Payement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\CotisationController::makeSucess()": the $pay argument is type-hinted with the non-existent class or interface: "App\\Service\\PayTech\\Payement".');
    }
}
