<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M6h3hhCService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.m6h3hhC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m6h3hhC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dmd' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'membreRipo' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService', true],
        ], [
            'dmd' => 'App\\Repository\\DemandeRepository',
            'manager' => '?',
            'membreRipo' => 'App\\Repository\\MembreRepository',
        ]);
    }
}
