<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dj8T8ljService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.dj8T8lj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dj8T8lj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'themRepo' => ['privates', 'App\\Repository\\ThematiqueRepository', 'getThematiqueRepositoryService', true],
        ], [
            'em' => '?',
            'themRepo' => 'App\\Repository\\ThematiqueRepository',
        ]);
    }
}
