<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZqLTNQHService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zqLTNQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zqLTNQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catRepo' => ['privates', 'App\\Repository\\CategorieArticleRepository', 'getCategorieArticleRepositoryService', true],
        ], [
            'catRepo' => 'App\\Repository\\CategorieArticleRepository',
        ]);
    }
}
