<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7gRzEyFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.7gRzEyF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7gRzEyF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cateRipo' => ['privates', 'App\\Repository\\CategorieEvenementRepository', 'getCategorieEvenementRepositoryService', true],
            'evRipo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'cateRipo' => 'App\\Repository\\CategorieEvenementRepository',
            'evRipo' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
