<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BliN7C9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bliN7C9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bliN7C9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'footRepo' => ['privates', 'App\\Repository\\FooterRepository', 'getFooterRepositoryService', true],
        ], [
            'em' => '?',
            'footRepo' => 'App\\Repository\\FooterRepository',
        ]);
    }
}
