<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ai9oNmKService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ai9oNmK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ai9oNmK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'comRepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'imageRepo' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
        ], [
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'comRepo' => 'App\\Repository\\CommentaireRepository',
            'imageRepo' => 'App\\Repository\\ImageRepository',
        ]);
    }
}
