<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CLu61nyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.cLu61ny' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cLu61ny'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'sujetRepo' => ['privates', 'App\\Repository\\SujetRepository', 'getSujetRepositoryService', true],
            'thRepo' => ['privates', 'App\\Repository\\ThematiqueRepository', 'getThematiqueRepositoryService', true],
        ], [
            'paginator' => '?',
            'sujetRepo' => 'App\\Repository\\SujetRepository',
            'thRepo' => 'App\\Repository\\ThematiqueRepository',
        ]);
    }
}
