<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S8hN7_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.s8hN7_.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s8hN7_.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'payement' => ['privates', '.errored._o0OIL4', NULL, 'Cannot determine controller argument for "App\\Controller\\WalletController::recharge()": the $payement argument is type-hinted with the non-existent class or interface: "App\\Service\\PayTech\\Payement".'],
        ], [
            'payement' => '?',
        ]);
    }
}
