<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LVF8YuCService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.LVF8YuC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LVF8YuC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aboutRipo' => ['privates', 'App\\Repository\\PageAboutRepository', 'getPageAboutRepositoryService', true],
            'accueilRipo' => ['privates', 'App\\Repository\\PageAccueilRepository', 'getPageAccueilRepositoryService', true],
            'bureauRepository' => ['privates', 'App\\Repository\\PostesBureauRepository', 'getPostesBureauRepositoryService', true],
            'membreRipo' => ['privates', 'App\\Repository\\MembreBureauRepository', 'getMembreBureauRepositoryService', true],
            'partRipo' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService', true],
            'realRipo' => ['privates', 'App\\Repository\\RealisationRepository', 'getRealisationRepositoryService', true],
        ], [
            'aboutRipo' => 'App\\Repository\\PageAboutRepository',
            'accueilRipo' => 'App\\Repository\\PageAccueilRepository',
            'bureauRepository' => 'App\\Repository\\PostesBureauRepository',
            'membreRipo' => 'App\\Repository\\MembreBureauRepository',
            'partRipo' => 'App\\Repository\\PartenaireRepository',
            'realRipo' => 'App\\Repository\\RealisationRepository',
        ]);
    }
}
