<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QzMJ_0cService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.qzMJ.0c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qzMJ.0c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coRepo' => ['privates', 'App\\Repository\\CotisationRepository', 'getCotisationRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'walletRipo' => ['privates', 'App\\Repository\\WalletRepository', 'getWalletRepositoryService', true],
        ], [
            'coRepo' => 'App\\Repository\\CotisationRepository',
            'manager' => '?',
            'walletRipo' => 'App\\Repository\\WalletRepository',
        ]);
    }
}
