<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ejdr4EiService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ejdr4Ei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ejdr4Ei'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cotisationRipo' => ['privates', 'App\\Repository\\CotisationRepository', 'getCotisationRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'membreRipo' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService', true],
        ], [
            'cotisationRipo' => 'App\\Repository\\CotisationRepository',
            'em' => '?',
            'membreRipo' => 'App\\Repository\\MembreRepository',
        ]);
    }
}
