<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BghVpYnService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BghVpYn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BghVpYn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comRepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'subRepo' => ['privates', 'App\\Repository\\SujetRepository', 'getSujetRepositoryService', true],
            'thRepo' => ['privates', 'App\\Repository\\ThematiqueRepository', 'getThematiqueRepositoryService', true],
        ], [
            'comRepo' => 'App\\Repository\\CommentaireRepository',
            'subRepo' => 'App\\Repository\\SujetRepository',
            'thRepo' => 'App\\Repository\\ThematiqueRepository',
        ]);
    }
}
