<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ku_C2QLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ku.c2QL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ku.c2QL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depotRepo' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'depotRepo' => 'App\\Repository\\DepotRepository',
            'em' => '?',
            'paginator' => '?',
        ]);
    }
}
