<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NNOo8KLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.NNOo8KL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NNOo8KL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depotRepo' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'depotRepo' => 'App\\Repository\\DepotRepository',
            'paginator' => '?',
        ]);
    }
}
