<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_543BcWXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.543BcWX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.543BcWX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cotisationRipo' => ['privates', 'App\\Repository\\CotisationRepository', 'getCotisationRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'membreRipo' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService', true],
            'pay' => ['privates', '.errored.93Njn1O', NULL, 'Cannot determine controller argument for "App\\Controller\\CotisationController::makeSucess()": the $pay argument is type-hinted with the non-existent class or interface: "App\\Service\\PayTech\\Payement".'],
        ], [
            'cotisationRipo' => 'App\\Repository\\CotisationRepository',
            'em' => '?',
            'membreRipo' => 'App\\Repository\\MembreRepository',
            'pay' => '?',
        ]);
    }
}
