<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V0qMe2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.V0q_me2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V0q_me2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cateRipo' => ['privates', 'App\\Repository\\CategorieEvenementRepository', 'getCategorieEvenementRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'evRipo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'cateRipo' => 'App\\Repository\\CategorieEvenementRepository',
            'em' => '?',
            'evRipo' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
