<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W6k0vBdService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.w6k0vBd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6k0vBd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'posteRipo' => ['privates', 'App\\Repository\\PostesBureauRepository', 'getPostesBureauRepositoryService', true],
        ], [
            'em' => '?',
            'posteRipo' => 'App\\Repository\\PostesBureauRepository',
        ]);
    }
}
