<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2c4prNnService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.2c4prNn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2c4prNn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ripo' => ['privates', 'App\\Repository\\CategorieEvenementRepository', 'getCategorieEvenementRepositoryService', true],
        ], [
            'ripo' => 'App\\Repository\\CategorieEvenementRepository',
        ]);
    }
}
