<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Emfj6CuService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.emfj6Cu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.emfj6Cu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cateRipo' => ['privates', 'App\\Repository\\CategorieEvenementRepository', 'getCategorieEvenementRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'partRipo' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService', true],
            'ripo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'cateRipo' => 'App\\Repository\\CategorieEvenementRepository',
            'paginator' => '?',
            'partRipo' => 'App\\Repository\\PartenaireRepository',
            'ripo' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
