<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VO5kdm2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.VO5kdm2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VO5kdm2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prodRepo' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'prodRepo' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
