<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Rbt0ZAOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.Rbt0ZAO' shared service.
     *
     * @return \App\Service\PayTech\Payement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\CommandeController::addCommande()": the $payement argument is type-hinted with the non-existent class or interface: "App\\Service\\PayTech\\Payement".');
    }
}
