<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GyeN4f1Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gyeN4f1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gyeN4f1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cmdRipo' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'cmdRipo' => 'App\\Repository\\CommandeRepository',
            'em' => '?',
        ]);
    }
}
