<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminBureauControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminBureauController' shared autowired service.
     *
     * @return \App\Controller\AdminBureauController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminBureauController'] = $instance = new \App\Controller\AdminBureauController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\PostesBureauRepository'] ?? $container->load('getPostesBureauRepositoryService')), ($container->privates['App\\Repository\\MembreBureauRepository'] ?? $container->load('getMembreBureauRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AdminBureauController', $container));

        return $instance;
    }
}
