<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnuaireControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AnnuaireController' shared autowired service.
     *
     * @return \App\Controller\AnnuaireController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AnnuaireController'] = $instance = new \App\Controller\AnnuaireController(($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AnnuaireController', $container));

        return $instance;
    }
}
