<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEntrepriseControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminEntrepriseController' shared autowired service.
     *
     * @return \App\Controller\AdminEntrepriseController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminEntrepriseController'] = $instance = new \App\Controller\AdminEntrepriseController(($container->privates['App\\Repository\\EntrepriseRepository'] ?? $container->load('getEntrepriseRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AdminEntrepriseController', $container));

        return $instance;
    }
}
