<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPageAboutControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminPageAboutController' shared autowired service.
     *
     * @return \App\Controller\AdminPageAboutController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminPageAboutController'] = $instance = new \App\Controller\AdminPageAboutController(($container->privates['App\\Repository\\PageAboutRepository'] ?? $container->load('getPageAboutRepositoryService')), ($container->privates['App\\Repository\\RealisationRepository'] ?? $container->load('getRealisationRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AdminPageAboutController', $container));

        return $instance;
    }
}
