<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDemandePartenariatControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminDemandePartenariatController' shared autowired service.
     *
     * @return \App\Controller\AdminDemandePartenariatController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminDemandePartenariatController'] = $instance = new \App\Controller\AdminDemandePartenariatController(($container->privates['App\\Repository\\PartenariatRepository'] ?? $container->load('getPartenariatRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AdminDemandePartenariatController', $container));

        return $instance;
    }
}
