<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonneControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AbonneController' shared autowired service.
     *
     * @return \App\Controller\AbonneController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AbonneController'] = $instance = new \App\Controller\AbonneController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AbonneController', $container));

        return $instance;
    }
}
