<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPageAccueilControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminPageAccueilController' shared autowired service.
     *
     * @return \App\Controller\AdminPageAccueilController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminPageAccueilController'] = $instance = new \App\Controller\AdminPageAccueilController(($container->privates['App\\Repository\\PageAccueilRepository'] ?? $container->load('getPageAccueilRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AdminPageAccueilController', $container));

        return $instance;
    }
}
