<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AgendaController' shared autowired service.
     *
     * @return \App\Controller\AgendaController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AgendaController'] = $instance = new \App\Controller\AgendaController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AgendaController', $container));

        return $instance;
    }
}
