<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAddAccountControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminAddAccountController' shared autowired service.
     *
     * @return \App\Controller\AdminAddAccountController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminAddAccountController'] = $instance = new \App\Controller\AdminAddAccountController(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\AdminAddAccountController', $container));

        return $instance;
    }
}
