<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotAdminControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DepotAdminController' shared autowired service.
     *
     * @return \App\Controller\DepotAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DepotAdminController'] = $instance = new \App\Controller\DepotAdminController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\DepotAdminController', $container));

        return $instance;
    }
}
