<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmploisDetailsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EmploisDetailsController' shared autowired service.
     *
     * @return \App\Controller\EmploisDetailsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EmploisDetailsController'] = $instance = new \App\Controller\EmploisDetailsController(($container->privates['App\\Repository\\OffreEmploisRepository'] ?? $container->load('getOffreEmploisRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\EmploisDetailsController', $container));

        return $instance;
    }
}
