<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFormAuthentificatorAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\LoginFormAuthentificatorAuthenticator' shared autowired service.
     *
     * @return \App\Security\LoginFormAuthentificatorAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\LoginFormAuthentificatorAuthenticator'] = new \App\Security\LoginFormAuthentificatorAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
