<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembreProfileControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MembreProfileController' shared autowired service.
     *
     * @return \App\Controller\MembreProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MembreProfileController'] = $instance = new \App\Controller\MembreProfileController(($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\Mail\\ApiMailVerification'] ?? ($container->privates['App\\Service\\Mail\\ApiMailVerification'] = new \App\Service\Mail\ApiMailVerification())));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\MembreProfileController', $container));

        return $instance;
    }
}
