<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostesBureauRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PostesBureauRepository' shared autowired service.
     *
     * @return \App\Repository\PostesBureauRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PostesBureauRepository'] = new \App\Repository\PostesBureauRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
