<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SocialsController' shared autowired service.
     *
     * @return \App\Controller\SocialsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SocialsController'] = $instance = new \App\Controller\SocialsController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\SocialsController', $container));

        return $instance;
    }
}
