<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuperAdminRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SuperAdminRepository' shared autowired service.
     *
     * @return \App\Repository\SuperAdminRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SuperAdminRepository'] = new \App\Repository\SuperAdminRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
