<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThematiqueControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ThematiqueController' shared autowired service.
     *
     * @return \App\Controller\ThematiqueController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ThematiqueController'] = $instance = new \App\Controller\ThematiqueController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ThematiqueController', $container));

        return $instance;
    }
}
