<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThematiqueRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ThematiqueRepository' shared autowired service.
     *
     * @return \App\Repository\ThematiqueRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ThematiqueRepository'] = new \App\Repository\ThematiqueRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
