<?php

namespace ContainerZhUc9iX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWalletControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\WalletController' shared autowired service.
     *
     * @return \App\Controller\WalletController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\WalletController'] = $instance = new \App\Controller\WalletController(($container->privates['App\\Repository\\WalletRepository'] ?? $container->load('getWalletRepositoryService')), ($container->privates['App\\Repository\\MembreRepository'] ?? $container->load('getMembreRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->privates['App\\Repository\\DepotRepository'] ?? $container->load('getDepotRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\WalletController', $container));

        return $instance;
    }
}
