<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZhUc9iX\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhUc9iX/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZhUc9iX.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZhUc9iX\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZhUc9iX\App_KernelProdContainer([
    'container.build_hash' => 'ZhUc9iX',
    'container.build_id' => 'cffddee3',
    'container.build_time' => 1743279917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhUc9iX');
