<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PageAbout extends \App\Entity\PageAbout implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'missionTitre', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'missionText', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'motTitre', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'motContenu', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'missionPath', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'motPath'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'missionTitre', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'missionText', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'motTitre', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'motContenu', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'missionPath', '' . "\0" . 'App\\Entity\\PageAbout' . "\0" . 'motPath'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PageAbout $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionTitre', []);

        return parent::getMissionTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionTitre(string $missionTitre): \App\Entity\PageAbout
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionTitre', [$missionTitre]);

        return parent::setMissionTitre($missionTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionText(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionText', []);

        return parent::getMissionText();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionText(string $missionText): \App\Entity\PageAbout
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionText', [$missionText]);

        return parent::setMissionText($missionText);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotTitre', []);

        return parent::getMotTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotTitre(string $motTitre): \App\Entity\PageAbout
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotTitre', [$motTitre]);

        return parent::setMotTitre($motTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotContenu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotContenu', []);

        return parent::getMotContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotContenu(string $motContenu): \App\Entity\PageAbout
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotContenu', [$motContenu]);

        return parent::setMotContenu($motContenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionPath(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionPath', []);

        return parent::getMissionPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionPath(?string $missionPath): \App\Entity\PageAbout
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionPath', [$missionPath]);

        return parent::setMissionPath($missionPath);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotPath(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotPath', []);

        return parent::getMotPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotPath(?string $motPath): \App\Entity\PageAbout
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotPath', [$motPath]);

        return parent::setMotPath($motPath);
    }

}
