<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Membre extends \App\Entity\Membre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'promotion', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'cv', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'wallet', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'entreprises', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'offreEmplois', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'profile', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'profession', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'secteur', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'entreprise', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'roleAmicale', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'bac', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'univ', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'diplome', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'experience', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'link', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'bio', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'cotisations', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'etat'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'promotion', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'cv', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'wallet', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'entreprises', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'offreEmplois', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'profile', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'profession', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'secteur', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'entreprise', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'roleAmicale', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'bac', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'univ', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'diplome', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'experience', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'link', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'bio', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'cotisations', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'etat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Membre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotion', []);

        return parent::getPromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotion(string $promotion): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotion', [$promotion]);

        return parent::setPromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(string $pays): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $telephone): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(bool $statut): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getCv(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCv', []);

        return parent::getCv();
    }

    /**
     * {@inheritDoc}
     */
    public function setCv(?string $cv): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCv', [$cv]);

        return parent::setCv($cv);
    }

    /**
     * {@inheritDoc}
     */
    public function getWallet(): ?\App\Entity\Wallet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWallet', []);

        return parent::getWallet();
    }

    /**
     * {@inheritDoc}
     */
    public function setWallet(?\App\Entity\Wallet $wallet): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWallet', [$wallet]);

        return parent::setWallet($wallet);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprises(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprises', []);

        return parent::getEntreprises();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntreprise(\App\Entity\Entreprise $entreprise): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntreprise', [$entreprise]);

        return parent::addEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntreprise(\App\Entity\Entreprise $entreprise): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntreprise', [$entreprise]);

        return parent::removeEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffreEmplois(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffreEmplois', []);

        return parent::getOffreEmplois();
    }

    /**
     * {@inheritDoc}
     */
    public function addOffreEmploi(\App\Entity\OffreEmplois $offreEmploi): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOffreEmploi', [$offreEmploi]);

        return parent::addOffreEmploi($offreEmploi);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOffreEmploi(\App\Entity\OffreEmplois $offreEmploi): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOffreEmploi', [$offreEmploi]);

        return parent::removeOffreEmploi($offreEmploi);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile(?string $profile): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', [$profile]);

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', []);

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession(?string $profession): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', [$profession]);

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecteur', []);

        return parent::getSecteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecteur(?string $secteur): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecteur', [$secteur]);

        return parent::setSecteur($secteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', []);

        return parent::getEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise(?string $entreprise): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', [$entreprise]);

        return parent::setEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleAmicale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleAmicale', []);

        return parent::getRoleAmicale();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleAmicale(?string $roleAmicale): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleAmicale', [$roleAmicale]);

        return parent::setRoleAmicale($roleAmicale);
    }

    /**
     * {@inheritDoc}
     */
    public function getBac(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBac', []);

        return parent::getBac();
    }

    /**
     * {@inheritDoc}
     */
    public function setBac(?string $bac): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBac', [$bac]);

        return parent::setBac($bac);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniv(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniv', []);

        return parent::getUniv();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniv(?string $univ): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniv', [$univ]);

        return parent::setUniv($univ);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiplome(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiplome', []);

        return parent::getDiplome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiplome(?string $diplome): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiplome', [$diplome]);

        return parent::setDiplome($diplome);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', []);

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperience(?string $experience): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperience', [$experience]);

        return parent::setExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', []);

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink(?string $link): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', [$link]);

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getBio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBio', []);

        return parent::getBio();
    }

    /**
     * {@inheritDoc}
     */
    public function setBio(?string $bio): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBio', [$bio]);

        return parent::setBio($bio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCotisations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCotisations', []);

        return parent::getCotisations();
    }

    /**
     * {@inheritDoc}
     */
    public function addCotisation(\App\Entity\Cotisation $cotisation): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCotisation', [$cotisation]);

        return parent::addCotisation($cotisation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCotisation(\App\Entity\Cotisation $cotisation): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCotisation', [$cotisation]);

        return parent::removeCotisation($cotisation);
    }

    /**
     * {@inheritDoc}
     */
    public function isEtat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEtat', []);

        return parent::isEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(?bool $etat): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticles', []);

        return parent::getArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticle(\App\Entity\Article $article): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticle', [$article]);

        return parent::addArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticle(\App\Entity\Article $article): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticle', [$article]);

        return parent::removeArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function getSujets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSujets', []);

        return parent::getSujets();
    }

    /**
     * {@inheritDoc}
     */
    public function addSujet(\App\Entity\Sujet $sujet): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSujet', [$sujet]);

        return parent::addSujet($sujet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSujet(\App\Entity\Sujet $sujet): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSujet', [$sujet]);

        return parent::removeSujet($sujet);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', []);

        return parent::getCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\App\Entity\Commande $commande): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', [$commande]);

        return parent::addCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\App\Entity\Commande $commande): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', [$commande]);

        return parent::removeCommande($commande);
    }

}
