<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OffreEmplois extends \App\Entity\OffreEmplois implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'id', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'domaine', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'createAt', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'endAt', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'description', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'membre'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'id', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'domaine', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'createAt', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'endAt', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'description', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\OffreEmplois' . "\0" . 'membre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OffreEmplois $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaine(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaine', []);

        return parent::getDomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaine(string $domaine): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaine', [$domaine]);

        return parent::setDomaine($domaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateAt', []);

        return parent::getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateAt(\DateTimeInterface $createAt): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateAt', [$createAt]);

        return parent::setCreateAt($createAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndAt', []);

        return parent::getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndAt(\DateTimeInterface $endAt): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndAt', [$endAt]);

        return parent::setEndAt($endAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(string $etat): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembre(): ?\App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembre', []);

        return parent::getMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMembre(?\App\Entity\Membre $membre): \App\Entity\OffreEmplois
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMembre', [$membre]);

        return parent::setMembre($membre);
    }

}
